#!/bin/bash
rcfiles=$HOME/.homesick/repos/dotfiles

system=`$rcfiles/system`

if [ -f ~/.localenv ]; then
	source ~/.localenv
fi

source $rcfiles/bash/colors

if [ "$system" == 'Linux' ]; then
	source $rcfiles/bash/rc.linux
fi
if [ "$system" == 'OSX' ]; then
	source $rcfiles/bash/rc.osx
fi

if [ ! -n "$HOSTNAME" ]; then
	HOSTNAME=`hostname -s`
fi

# Fix sorting of ls (dotfiles first!)
export LC_ALL="C"

source $rcfiles/aliases
source $rcfiles/bash/completion

# Set the custom prompt

# Username@host
PS1="${bldcyn}\u${txtwht}@${txtgrn}\h${txtwht}:"

# Stopped process count
PS1=$PS1'$( if [ $(jobs -s | wc -l) -gt 0 ]; then echo "[\j]"; fi )'

# Current directory
PS1=$PS1"${bldblu}\w"

# Current git branch
if type __git_ps1 >/dev/null 2>&1; then
    PS1=$PS1'$(__git_ps1 " (%s)")'
fi

# Finish the prompt
PS1=$PS1"$txtwht\$ $txtdef"

#autostart tmux
if [ "$PS1" != "" -a "${STARTED_TMUX:-x}" = x -a "${SSH_TTY:-x}" != x ]
then
    STARTED_TMUX=1; export STARTED_TMUX
    ~/.local/bin/tmux-shared remote && exit 0
    echo "tmux failed to start"
fi

unset rcfiles
unset system
