#!/bin/bash
rcfiles=$HOME/.homesick/repos/dotfiles

system=`$rcfiles/system`

# Set flag if this session is interactive
if [ -n "$PS1" ]; then
    INTERACTIVE_SESSION=true
fi

# Set up homeshick
source $HOME/.homesick/repos/homeshick/homeshick.sh

# Source local environment settings
if [ -f ~/.bash_local ]; then
    source ~/.bash_local
fi

# Source color aliases
source $rcfiles/bash/styling

# Source aliases settings
source $rcfiles/aliases

# Source platform-specific bashrc files
if [ "$system" == 'Linux' ]; then
    source $rcfiles/bash/rc.linux
fi
if [ "$system" == 'OSX' ]; then
    source $rcfiles/bash/rc.osx
fi

# Set hostname var if it doesn't exist
if [ ! -n "$HOSTNAME" ]; then
    HOSTNAME=`hostname -s`
fi

# Fix sorting of ls (dotfiles first!)
# C.UTF-8 is preferred (like C, but with utf8 support)
if locale -a | grep -qF 'C.UTF-8'; then
    loc="C.UTF-8"
else
    loc="en_US.UTF-8"
fi
export LANG=$loc
export LC_ALL=$loc

# Set Bash to vi mode
set -o vi

# Set default editor to Vim
export EDITOR=vim

# Ignore some controlling instructions
# HISTIGNORE is a colon-delimited list of patterns which should be excluded.
# The '&' is a special pattern which suppresses duplicate entries.
export HISTIGNORE=$'[ \t]*:&:[fb]g:exit:ls' # Ignore the ls command as well

# Don't put duplicate lines or lines starting with a space in the history.
export HISTCONTROL=ignoreboth

export HISTSIZE=32768
export HISTFILESIZE=$HISTSIZE

# Append to the history file, don't overwrite it
shopt -s histappend

# Check the window size after each command and, if necessary,
# Update the values of LINES and COLUMNS.
shopt -s checkwinsize

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob

# Autocorrect typos in path names when using `cd`
shopt -s cdspell

# Enable some Bash 4 features when possible:
# * `autocd`, e.g. `**/qux` will enter `./foo/bar/baz/qux`
# * Recursive globbing, e.g. `echo **/*.txt`
for option in autocd globstar; do
    shopt -s "$option" 2> /dev/null
done

# Prevent Ctrl-s and Ctrl-q from sending XOFF and XON signals
# Allows them to be used elsewhere
stty -ixon

##############################################################################
# INTERACTIVE SESSION ONLY

if $INTERACTIVE_SESSION; then

    ##########################################################################
    # PROMPT
    GIT_PS1_SHOWDIRTYSTATE=true

    # Username@host
    PS1="${txtitl}${txtcyn}\u${txtblu}@${txtgrn}\h${txtdef}"

    # Stopped process count
    PS1=$PS1${txtpur}'$( if [ $(jobs -s | wc -l) -gt 0 ]; then echo " [\j]"; fi )'${txtdef}

    # Current directory
    PS1=$PS1${txtblu}" \w"${txtdef}

    # Current git branch
    if type __git_ps1 >/dev/null 2>&1; then
        PS1=$PS1${txtylw}'$(__git_ps1 " (%s)")'${txtdef}
    fi

    # Finish the prompt
    PS1=$PS1"\n${txtpur}> ${txtdef}"

    ##########################################################################

    # Prioritize local bins in path
    export PATH="$HOME/bin:$HOME/.local/bin:$PATH"

    # set the terminfo such that it also works via ssh
    tic ~/.homesick/repos/dotfiles/terminal/xterm-256color.terminfo
    tic ~/.homesick/repos/dotfiles/terminal/tmux-256color.terminfo

    # # autostart tmux
    # if [ "$PS1" != "" -a "${TMUX}" == "" -a "${SSH_TTY:-x}" != x ]; then
    #     # attempt to discover a detached session and attach it,
    #     # else create a new session
    #     WHOAMI=$(whoami)
    #     tmux -f ~/.tmux/conf/tmux.conf new-session -A -s $WHOAMI
    # fi

    # added by Miniconda2 4.3.21 installer
    # export PATH="$HOME/.miniconda2/bin:$PATH"

    # Add rust to path
    export PATH="$HOME/.cargo/bin:$PATH"

    # initialize fzf
    [ -f ~/.fzf.bash ] && source ~/.fzf.bash

    # initialize nvm
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

    # initialize pyenv
    export PATH="~/.pyenv/bin:$PATH"
    if command -v pyenv 1>/dev/null 2>&1; then
      eval "$(pyenv init -)"
    fi

    # initizlize serverless

    # tabtab source for serverless package
    # uninstall by removing these lines or running `tabtab uninstall serverless`
    [ -f ~/n/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.bash ] && . ~/n/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.bash
    # tabtab source for sls package
    # uninstall by removing these lines or running `tabtab uninstall sls`
    [ -f ~/n/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.bash ] && . ~/n/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.bash

    # The next line updates PATH for the Google Cloud SDK.
    if [ -f '/Users/bennett/Downloads/google-cloud-sdk/path.bash.inc' ]; then source '/Users/bennett/Downloads/google-cloud-sdk/path.bash.inc'; fi

    # The next line enables shell command completion for gcloud.
    if [ -f '/Users/bennett/Downloads/google-cloud-sdk/completion.bash.inc' ]; then source '/Users/bennett/Downloads/google-cloud-sdk/completion.bash.inc'; fi


fi

##############################################################################

# Clean up
unset rcfiles
unset system
